### ISSUE TITLE
What after encryption ?

### ISSUE THREAD

**Issue by yesiamdollar** [Chainski/AES-Encoder#4]
I have encrypt file as mentioned in your README.md file, but what after that, how I can run the script after encryption ? it will be useful if you add it in the README.md file.

**Comment by chainski** [comment]
> I have encrypt file as mentioned in your README.md file, but what after that, how I can run the script after encryption ? it will be useful if you add it in the README.md file.

Right click on the ```ps1``` file and select run with powershell  
![image](https://github.com/Chainski/AES-Encoder/assets/96607632/78f02d8b-422a-4bdb-b996-86d6a8d86fb8)

or 

Try navigating to wherever the script is
ps> cd C:\scriptlocation
then run your command
```PowerShell -ExecutionPolicy Bypass -File .\encrypted.ps1```
or reference the location in the -file parameter
```PowerShell -ExecutionPolicy Bypass -File "c:\script_location\encrypted.ps1"```
