### ISSUE TITLE
project used in a malware

### ISSUE THREAD

**Issue by simotone97** [Chainski/AES-Encoder#7]
Hi, I just wanna say that unfortunately your awesome script is being actively used in a malware sample. Specifically [this](https://app.any.run/tasks/7a7227f0-85b2-4e8f-85d0-9b4950cd7ab2/) sample uses a base64 string (plaintext in the .exe, you can see with PEStudio) which can be decoded into a staging link where your AES-Encoder is hosted and then used by the malware. I know it is not your fault, I just wanna inform you of the abuse.
Best regards

**Comment by 5Noxi** [comment]
Which version did you use? The one from main path or the one from the releases?
